### ISSUE TITLE
无法通过编译

### ISSUE THREAD

**Issue by zwh-china** [zhongyang219/SimpleNotePad#2]
IDE：vs2017
错误信息：simplenotepad-1.25\simplenotepad\simplenotepaddlg.cpp(388): error C2440: “static_cast”: 无法从“LONG (__cdecl CSimpleNotePadDlg::* )(WPARAM,LPARAM)”转换为“LRESULT (__cdecl CWnd::* )(WPARAM,LPARAM)”

**Comment by zhongyang219** [comment]
我这里是能编译通过的，至于你为什么会出现这个问题，我也不清楚。

**Comment by zhongyang219** [comment]
x64下确实存在这个问题，已经解决。
