### ISSUE TITLE
是否可以实现右击文件Edit With SimpleNotePad

### ISSUE THREAD

**Issue by lovezhangtao** [zhongyang219/SimpleNotePad#23]
![image](https://user-images.githubusercontent.com/22004897/201255410-1dcf5adb-c974-4a45-9d93-dd5a45ab3a7b.png)
是否可以像NotePad++一样，通过右击文件Edit With SimpleNotePad
来打开呢

**Comment by lovezhangtao** [comment]
@zhongyang219 能否看一下 谢谢

**Comment by zhongyang219** [comment]
这个功能已经有了，请更新到最新版本。

**Comment by lovezhangtao** [comment]
@zhongyang219 
已下载最新版本了，右击还是没有
请问release的版本都是portable的形式
如何做到右击Edit With SimpleNotePad ？需要额外的设置吗？

**Comment by zhongyang219** [comment]
菜单栏“工具”——“选项”——“常规设置”，勾选“添加到资源管理器右键菜单”
![image](https://user-images.githubusercontent.com/30562462/203515162-41ee0d9a-0982-4578-999d-fa2d73981e01.png)

**Comment by lovezhangtao** [comment]
设置后，确认OK
谢谢！
