### ISSUE TITLE
请问哪个部分是最基础的

### ISSUE THREAD

**Issue by cupcakefromchina** [zhongyang219/SimpleNotePad#3]
您好，如果我想照着您的工作重新造一个，我应该从哪个部分开始呢？

**Comment by zhongyang219** [comment]
文本显示和编辑功能当然是最基本的。
如果你想自己学着做一个类似的软件，你可以先做一个有打开和保存txt文件功能的软件。在此基础上，你可能还需要考虑增加另存为、新建、关闭时询问是否保存的逻辑。然后是编码格式自动识别、编码格式转换、查找替换、字体设置等功能。

**Comment by cupcakefromchina** [comment]
> 文本显示和编辑功能当然是最基本的。
> 如果你想自己学着做一个类似的软件，你可以先做一个有打开和保存txt文件功能的软件。在此基础上，你可能还需要考虑增加另存为、新建、关闭时询问是否保存的逻辑。然后是编码格式自动识别、编码格式转换、查找替换、字体设置等功能。

感谢您的建议:)
